services:
  postgres:
    image: postgres:15-alpine
    container_name: donation-platform-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: donation_platform
    ports:
      - "5436:5432"
    volumes:
      - donation_platform_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  donation_platform_postgres_data:
    driver: local
